version: '3'

services:
  goal-redis:
    image: redis
    container_name: goal-redis
    ports:
      - '6378:6379'
    volumes:
      # Create these volumes on the project root directory
      - ./goal_redis:/data

  goal-flower:
    image: mher/flower
    container_name: goal-flower
    command: ['flower', '--port=8888']
    environment:
      - CELERY_BROKER_URL=redis://goal-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://goal-redis:6379/0
      - FLOWER_PORT=8888
    depends_on:
      - goal-api
      - goal-redis
    ports:
      - '8888:8888'

  goal-api:
    build: .
    image: goal-api
    container_name: goal-api
    ports:
      - '1000:8000'
    volumes:
      # Create these volumes on the project root directory
      - .:/goal-api
    depends_on:
      - goal-db
      - goal-redis

  goal-db:
    restart: always
    image: postgres:11
    container_name: goal-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goal_db
    volumes:
      # Create these volumes on the project root directory
      - ./goal_db:/var/lib/postgresql/data
    ports:
      - '5433:5432'
