version: "3"

services:
  tudo-redis:
    image: redis
    container_name: tudo-redis
    ports:
      - "6378:6379"
    volumes:
      # Create these volumes on the project root directory
      - ./tudo_redis:/data

  tudo-flower:
    image: mher/flower
    container_name: tudo-flower
    command: ["flower", "--port=8888"]
    environment:
      - CELERY_BROKER_URL=redis://tudo-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://tudo-redis:6379/0
      - FLOWER_PORT=8888
    depends_on:
      - tudo-api
      - tudo-redis
    ports:
      - "8888:8888"

  tudo-api:
    build: .
    image: tudo-api
    container_name: tudo-api
    ports:
      - "1000:8000"
    volumes:
      # Create these volumes on the project root directory
      - .:/tudo-api
    depends_on:
      - tudo-db
      - tudo-redis

  tudo-db:
    restart: always
    image: postgres:11
    container_name: tudo-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tudo_db
    volumes:
      # Create these volumes on the project root directory
      - ./tudo_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
