version: '3.3'

services:
  goal-api:
    build: .
    image: goal-api:prod
    container_name: goal-api
    restart: unless-stopped
    ports:
      - '1000:8000'
    volumes:
      - .:/goal-api
  goal-redis:
    image: redis
    container_name: goal-redis
    restart: unless-stopped
    ports:
      - '6378:6379'
    volumes:
      - ./goal_redis:/data
