version: "3.3"

services:
  tudo-api:
    build: .
    image: tudo-api:staging
    container_name: tudo-api
    restart: unless-stopped
    ports:
      - "1000:8000"
    volumes:
      - .:/tudo-api
    depends_on:
      - tudo-redis

  tudo-redis:
    image: redis
    container_name: tudo-redis
    restart: unless-stopped
    ports:
      - "6378:6379"
    volumes:
      # Create these volumes on the project root directory
      - ./tudo_redis:/data
