version: '3.3'

services:
  goal-api:
    build: .
    image: goal-api:staging
    container_name: goal-api
    restart: unless-stopped
    ports:
      - '1000:8000'
    volumes:
      - .:/goal-api
    depends_on:
      - goal-redis

  goal-redis:
    image: redis
    container_name: goal-redis
    restart: unless-stopped
    ports:
      - '6378:6379'
    volumes:
      # Create these volumes on the project root directory
      - ./goal_redis:/data
